# Fly.io app configuration
app="inbound-carrier-sales-ff0ca6ba"
primary_region = "iad"

[build]
# Uses Dockerfile in project root

[env]
  # Update to your Fly app URL if you rename the app
  NEXT_PUBLIC_BASE_URL = "https://inbound-carrier-sales-ff0ca6ba.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft = 20
    hard = 30

  [[http_service.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "20s"
    method = "get"
    path = "/"
    protocol = "http"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"


